#ifndef STRINGS_CZ_H
#define STRINGS_CZ_H

#define SCR_SETTINGS                  (uint8_t *)"Nastavení:"
#define SCR_SET_DATE_TIME             (uint8_t *)"Nastavení data a času"
#define SCR_SET_DISPLAY               (uint8_t *)"Nastavení displeje"
#define SCR_SETTINGS_SND              (uint8_t *)"Nastavení notifikací"
#define SCR_SET_SECU                  (uint8_t *)"Nastavení zabezpečení"
#define SD_UMOUNT                     (uint8_t *)"Odpojit SD kartu"
#define SCR_ABOUT_SYSTEM              (uint8_t *)"O Systému"
#define SCR_SET_TIME_SCR              (uint8_t *)"Nastavení data a času:"
#define SCR_SET_TIME                  (uint8_t *)"Nastavit čas"
#define SCR_SET_DATE                  (uint8_t *)"Nastavit datum"
#define SCR_BACK                      (uint8_t *)"Zpět"
#define SCR_DISPLAY_SETTINGS_SCREEN   (uint8_t *)"Nastavení Displeje:"
#define SCR_COLOR_SETTINGS            (uint8_t *)"Nastevení barev"
#define SCR_LCD_CALIB                 (uint8_t *)"Kalibrace"
#define SCR_DISPLAY_SHDN_TIME         (uint8_t *)"Displej se vypne za:"
#define SCR_BACKLIGHT                 (uint8_t *)"Podsvícení:"
#define SCR_STORE                     (uint8_t *)"Uložit"
#define SCR_COLOR_SETTINGS_SCREEN     (uint8_t *)"Nastavení barev:"

#define SCR_BORDER_COLOR              (uint8_t *)"Border color"
#define SCR_TEXT_COLOR                (uint8_t *)"Text color"
#define SCR_BG_COLOR                  (uint8_t *)"Background color"
#define SCR_FILL_COLOR                (uint8_t *)"Fill color"
#define SCR_ACTIVE_COLOR              (uint8_t *)"Active color"
#define SCR_SET_DEFAULTS              (uint8_t *)"Nastavit výchozí"
#define SCR_NOTIFICATIONS             (uint8_t *)"Nastavení zvuku:"
#define SCR_SOUND_OFF                 (uint8_t *)"Ztlumit zvuk"
#define SCR_SECURITY_SCREEN           (uint8_t *)"Nastavení zabezpečení:"
#define SCR_OLD_PASSWORD              (uint8_t *)"Původní heslo:"
#define SCR_NEW_PASSWORD              (uint8_t *)"Nové heslo:"
#define SCR_CHANGE_PASSWORD           (uint8_t *)"Změnit"
#define SCR_WRONG_PASSWORD            (uint8_t *)"Špatné heslo!"
#define SCR_PASSWORD_STORED           (uint8_t *)"Heslo uloženo."
#define SCR_OS_VERSION                (uint8_t *)"SDA OS verze "
#define SCR_BATT_VOLTAGE              (uint8_t *)"Napětí baterie:"
#define SCR_UPTIME                    (uint8_t *)"Doba běhu:"
#define SCR_SCREEN_ON_TIME            (uint8_t *)"Z toho LCD zapnuto:"
#define SCR_BATT_PWR_TIME             (uint8_t *)"Doba běhu z baterie:"
#define SCR_SD_MOUNT                  (uint8_t *)"Připojit SD kartu"
#define SCR_SD_NOT_PRESENT_WARNING    (uint8_t *)"Nejprv připojte SD kartu"
#define SCR_CARD_ERROR_REPEAT         (uint8_t *)"Chyba karty, opakovat?"
#define SCR_SOUND_ON                  (uint8_t *)"Zvuk zapnut"

#define OVRL_ENTER_TIME               (uint8_t *)"Zadejte Čas:"
#define OVRL_OK                       (uint8_t *)"Ok"
#define OVRL_CANCEL                   (uint8_t *)"Zrušit"
#define OVRL_SELECT_COLOR             (uint8_t *)"Zvolte barvu:"
#define OVRL_MON1                     (uint8_t *)"Leden"
#define OVRL_MON2                     (uint8_t *)"Únor"
#define OVRL_MON3                     (uint8_t *)"Březen"
#define OVRL_MON4                     (uint8_t *)"Duben"
#define OVRL_MON5                     (uint8_t *)"Květen"
#define OVRL_MON6                     (uint8_t *)"Červen"
#define OVRL_MON7                     (uint8_t *)"Červenec"
#define OVRL_MON8                     (uint8_t *)"Srpen"
#define OVRL_MON9                     (uint8_t *)"Září"
#define OVRL_MON10                    (uint8_t *)"Říjen"
#define OVRL_MON11                    (uint8_t *)"Listopad"
#define OVRL_MON12                    (uint8_t *)"Prosinec"
#define OVRL_DAY1                     (uint8_t *)"Po"
#define OVRL_DAY2                     (uint8_t *)"Út"
#define OVRL_DAY3                     (uint8_t *)"St"
#define OVRL_DAY4                     (uint8_t *)"Čt"
#define OVRL_DAY5                     (uint8_t *)"Pá"
#define OVRL_DAY6                     (uint8_t *)"So"
#define OVRL_DAY7                     (uint8_t *)"Ne"
#define OVRL_ENTER_DATE               (uint8_t *)"Zvolte datum:"
#define OVRL_SILENT                   (uint8_t *)"Tichý režim"
#define OVRL_ERROR                    (uint8_t *)"Nastala chyba:"

#define ASCR_CARD_ERROR               (uint8_t *)"Chyba Karty"
#define ASCR_FILE_ERROR               (uint8_t *)"Chyba Souboru"
#define ASCR_NONAME                   (uint8_t *)"Není název"
#define ASCR_APPLICATIONS             (uint8_t *)"Programy:"
#define ASCR_RUNNING_APP              (uint8_t *)"Běžící aplikace"

#define SWICH_RUNNING_APPS            (uint8_t *)"Běžící procesy:"
#define SWITCH_CLOSE_ALL              (uint8_t *)"Zavřit vše"

#define SCR_LED_NOTIFICATIONS         (uint8_t *)"Notifikační LED"
#define IRQ_BATT_CHRG                 (uint8_t *)" NAB."


#endif
