#ifndef STRINGS_EN_H
#define STRINGS_EN_H

#define SCR_SETTINGS                                  (uint8_t*)"Settings:"
#define SCR_SET_DATE_TIME                             (uint8_t*)"Time and date"
#define SCR_SET_DISPLAY                               (uint8_t*)"Display"
#define SCR_SETTINGS_SND                              (uint8_t*)"Notifications"
#define SCR_SET_SECU                                  (uint8_t*)"Security"
#define SD_UMOUNT                                     (uint8_t*)"Unmount the SD card"
#define SCR_ABOUT_SYSTEM                              (uint8_t*)"About"
#define SCR_SET_TIME_SCR                              (uint8_t*)"Time and date settings:"
#define SCR_SET_TIME                                  (uint8_t*)"Set time"
#define SCR_SET_DATE                                  (uint8_t*)"Set date"
#define SCR_BACK                                      (uint8_t*)"Back"
#define SCR_DISPLAY_SETTINGS_SCREEN                   (uint8_t*)"Display settings:"
#define SCR_COLOR_SETTINGS                            (uint8_t*)"Color settings"
#define SCR_LCD_CALIB                                 (uint8_t*)"Touch calibration"
#define SCR_DISPLAY_SHDN_TIME                         (uint8_t*)"Display shutdown time:"
#define SCR_BACKLIGHT                                 (uint8_t*)"Backlight:"
#define SCR_STORE                                     (uint8_t*)"Store"
#define SCR_COLOR_SETTINGS_SCREEN                     (uint8_t*)"Color settings:"

#define SCR_BORDER_COLOR                              (uint8_t*)"Border color"
#define SCR_TEXT_COLOR                                (uint8_t*)"Text color"
#define SCR_BG_COLOR                                  (uint8_t*)"Background color"
#define SCR_FILL_COLOR                                (uint8_t*)"Fill color"
#define SCR_ACTIVE_COLOR                              (uint8_t*)"Active color"
#define SCR_SET_DEFAULTS                              (uint8_t*)"Set default"
#define SCR_NOTIFICATIONS                             (uint8_t*)"Sound settings:"
#define SCR_SOUND_OFF                                 (uint8_t*)"Sound OFF"
#define SCR_SECURITY_SCREEN                           (uint8_t*)"Security settings:"
#define SCR_OLD_PASSWORD                              (uint8_t*)"Old password::"
#define SCR_NEW_PASSWORD                              (uint8_t*)"New password:"
#define SCR_CHANGE_PASSWORD                           (uint8_t*)"Apply change"
#define SCR_LOCK_DEVICE                               (uint8_t*)"Lock device"
#define SCR_RESET_KEY                                 (uint8_t*)"Reset key"
#define SCR_WRONG_PASSWORD                            (uint8_t*)"Wrong password!"
#define SCR_PASSWORD_STORED                           (uint8_t*)"Password stored."
#define SCR_KEY_MISMATCH                              (uint8_t*)"Mismatched key and password"
#define SCR_OS_VERSION                                (uint8_t*)"SDA OS version "
#define SCR_BATT_VOLTAGE                              (uint8_t*)"Battery voltage:"
#define SCR_UPTIME                                    (uint8_t*)"Uptime:"
#define SCR_SCREEN_ON_TIME                            (uint8_t*)"LCD ON time:"
#define SCR_BATT_PWR_TIME                             (uint8_t*)"Time on battery power:"
#define SCR_SD_MOUNT                                  (uint8_t*)"Mount SD card"
#define SCR_SD_NOT_PRESENT_WARNING                    (uint8_t*)"SD Card not mounted!"
#define SCR_CARD_ERROR_MSG                            (uint8_t*)"Failed to mount the card."
#define SCR_SOUND_ON                                  (uint8_t*)"Sound ON"

#define OVRL_ENTER_TIME                               (uint8_t*)"Enter time:"
#define OVRL_OK                                       (uint8_t*)"Ok"
#define OVRL_CANCEL                                   (uint8_t*)"Back"
#define OVRL_SELECT_COLOR                             (uint8_t*)"Enter color:"
#define OVRL_MON1                                     (uint8_t*)"January"
#define OVRL_MON2                                     (uint8_t*)"February"
#define OVRL_MON3                                     (uint8_t*)"March"
#define OVRL_MON4                                     (uint8_t*)"April"
#define OVRL_MON5                                     (uint8_t*)"May"
#define OVRL_MON6                                     (uint8_t*)"June"
#define OVRL_MON7                                     (uint8_t*)"July"
#define OVRL_MON8                                     (uint8_t*)"August"
#define OVRL_MON9                                     (uint8_t*)"September"
#define OVRL_MON10                                    (uint8_t*)"October"
#define OVRL_MON11                                    (uint8_t*)"November"
#define OVRL_MON12                                    (uint8_t*)"December"
#define OVRL_DAY1                                     (uint8_t*)"M"
#define OVRL_DAY2                                     (uint8_t*)"T"
#define OVRL_DAY3                                     (uint8_t*)"W"
#define OVRL_DAY4                                     (uint8_t*)"T"
#define OVRL_DAY5                                     (uint8_t*)"F"
#define OVRL_DAY6                                     (uint8_t*)"Sa"
#define OVRL_DAY7                                     (uint8_t*)"Su"
#define OVRL_ENTER_DATE                               (uint8_t*)"Enter date:"
#define OVRL_SILENT                                   (uint8_t*)"Silent mode"
#define OVRL_ERROR                                    (uint8_t*)"Error occurred:"
#define OVRL_ENTER_PASSWORD                           (uint8_t*)"Enter password:"
#define OVRL_GRANT_PERMISSIONS                        (uint8_t*)"Allow this application to change system settins?"
#define SCR_KEY_ERROR_MSG                             (uint8_t*)"Given password doesn\'t match the device encryption key."
#define OVRL_SEC_NOT_SET_UP                           (uint8_t*)"Not configured!"

#define ASCR_CARD_ERROR                               (uint8_t*)"Card error!"
#define ASCR_FILE_ERROR                               (uint8_t*)"File error!"
#define ASCR_NONAME                                   (uint8_t*)"No name"
#define ASCR_APPLICATIONS                             (uint8_t*)"Applications:"
#define ASCR_RUNNING_APP                              (uint8_t*)"Running apps"
#define IRQ_BATT_CHRG                                 (uint8_t*)"Chrg."

#define SWITCH_RUNNING_APPS                           (uint8_t *)"Running applications:"
#define SWITCH_CLOSE_ALL                              (uint8_t *)"Close all"
#define MSG_ERROR_OCCURED                             (uint8_t *)"Error occured:"
#define SCR_LOADING_TEXT                              (uint8_t *)"Loading..."

#endif
